baseURL = 'https://klokreparatiejoure.nl'
languageCode = 'nl-NL'
paginate = 6
theme= 'cohub'
title = 'Freerk Pasveer - Klokreparatie Joure'

[Menu]
  # Main Menu
  [[menu.Main]]
  name = "Reparatie"
  url= "#reparatie"
  weight = 1
  [[menu.Main]]
  name = "Over"
  url= "#over"
  weight = 2
  [[menu.Main]]
  name = "Stoel-en staartklokken"
  url= "#klokken"
  weight = 3
  [[menu.Main]]
  name = "Contact"
  url= "/contact/"
  weight = 7

  # Sitemap Menu
  [[menu.sitemap]]
  name = "Privacy Policy"
  url = "/privacy/"
  weight = 1
  [[menu.sitemap]]
  name = "Terms"
  url = "/terms/"
  weight = 2

[params]
  aboutPageURL = "over"
  contactLink = "contact"
  copyright = "© {year}"
  logo = "images/logo.png"
  footerlogo = "images/logo.png"
  footerDescription = "Freerk Pasveer - Klokreparatie Joure"

  [params.address]
  address = "Midstraat 37 \n 8501 AD Joure"
  email = "info@klokreparatiejoure.nl"
  openingDesc = "De openingstijden kunnen afwijken vanwege klantbezoeken. Bel of mail voor een afspraak."
  openingHours = "Ma. t/m donderdag : 9:00 - 17:00 uur \n Vrijdag : 9:00 - 17:00 uur \n Zaterdag: 10:00 - 16:00 uur \n Lunchpauze: 12:00 - 13:00 uur \n Opening op afspraak is mogelijk."
  phone = "+31657552938"

  [params.map]
  APIkey = "AIzaSyC9rV6yesIygoVKTD6QLf_iCa9eiIIHqZ0"
  latitude = "52.9687785"
  longitude = "5.7915066"
  pinImage = "images/pin.png"

  # Socail icons
  [[params.social]]
  icon = "ti-instagram"
  url = "https://www.instagram.com/"
  weight = 1
